meta:
  name: SuperPlanners
  version: 1.0.0
  updated: 2026-04-14T19:20:44.474Z
projects:
  - project_id: phase2-python-engine
    project: phase2-python-engine
    status: active
    updated: 2026-04-14T09:27:18.417Z
    path: phase2-python-engine/tasks.yaml
  - project_id: phase3-self-improvement
    project: phase3-self-improvement
    status: active
    updated: 2026-04-14T19:20:44.468Z
    path: phase3-self-improvement/tasks.yaml
